listen_port: 8080
target_url: "http://localhost:9999"

# Log level can be: debug, info, warn, error
log_level: "info"

# API key configuration (optional)
# If not configured, nexus will pass through client API keys directly
api_keys:
  # Map of client API keys to upstream API keys
  # Format: "client_key": "upstream_key"
  "nexus-client-demo": "sk-upstream-demo-key"
  "nexus-client-user1": "sk-upstream-demo-key" 
  "nexus-client-user2": "sk-upstream-demo-key"

limits:
  # Tier 1: A basic backstop for server health
  requests_per_second: 2
  burst: 3

  # Tier 2: The core feature for cost control
  # This limit is applied per-API-key.
  model_tokens_per_minute: 1000

# TLS configuration (optional)
# Uncomment and configure to enable HTTPS
# tls:
#   enabled: true
#   cert_file: "/path/to/cert.pem"
#   key_file: "/path/to/key.pem"

# Metrics configuration
metrics:
  enabled: true
  metrics_endpoint: "/metrics"
  prometheus_enabled: true
  json_export_enabled: true
  csv_export_enabled: true
  auth_required: false
  mask_api_keys: true
