name: CI

on:
  push:
    branches: [ main, develop, 'feat/**', 'fix/**', 'docs/**', 'chore/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint  # Only run tests if linting passes
    strategy:
      matrix:
        go-version: ['1.22', '1.23']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Download dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Run tests with coverage
        run: |
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html
        if: matrix.go-version == '1.23'

      - name: Check coverage threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Total coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage is below 70% threshold"
            exit 1
          fi
        if: matrix.go-version == '1.23'

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html
        if: matrix.go-version == '1.23'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]  # Only build if both linting and tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Download dependencies
        run: make deps

      - name: Build binary
        run: make build

      - name: Test version flag
        run: ./build/nexus -version

      - name: Test help flag
        run: ./build/nexus -help